export const ADD_ENTITY = 'ADD_ENTITY';
export const REMOVE_ENTITY = 'REMOVE_ENTITY';
export const CHANGE_ENTITY_HEALTH = 'CHANGE_ENTITY_HEALTH';
export const ADD_ENTITY_NOTE = 'ADD_ENTITY_NOTE';
export const REMOVE_ENTITY_NOTE = 'REMOVE_ENTITY_NOTE';
export const NEW_TURN = 'NEW_TURN';
export const CHANGE_ENTITY_ORDER = 'CHANGE_ENTITY_ORDER';
